In [19]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as pt
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
%matplotlib inline
df=pd.read_csv("C:\\Users\\29265\\Downloads\\data.csv")


In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
df.columns

Index(['Unnamed: 0', 'acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'key', 'liveness', 'loudness', 'mode',
       'speechiness', 'tempo', 'time_signature', 'valence', 'target',
       'song_title', 'artist'],
      dtype='object')

In [22]:
y=df['target']
x=df.drop(['target','song_title','artist'],axis=1)

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [13]:
X = StandardScaler().fit_transform(x.values)

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
df1 = pd.DataFrame(X)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,
                                                    random_state=42)

In [25]:
from sklearn.preprocessing import MinMaxScaler
pd.DataFrame(MinMaxScaler().fit_transform(x)).head()

0         1         2         3         4         5         6   \
0  0.000000  0.010248  0.824826  0.190735  0.426363  0.022439  0.181818   
1  0.000496  0.199998  0.720418  0.314481  0.350081  0.006260  0.090909   
2  0.000992  0.034570  0.830626  0.171624  0.403987  0.000240  0.181818   
3  0.001488  0.607034  0.431555  0.185488  0.328723  0.522541  0.454545   
4  0.001984  0.180902  0.645012  0.381202  0.555533  0.524590  0.454545   

         7         8    9         10        11    12        13  
0  0.153862  0.741141  1.0  0.514441  0.596033  0.75  0.262432  
1  0.124395  0.692162  1.0  0.071005  0.654474  0.75  0.577936  
2  0.147548  0.791369  1.0  0.335351  0.158539  0.75  0.144379  
3  0.077247  0.544709  1.0  0.003784  0.225162  0.75  0.203928  
4  0.442223  0.654132  0.0  0.058393  0.735659  0.75  0.908065

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,
                           p=2, metric='minkowski')
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [58]:
predictions = knn.predict(X_test)

In [59]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

             precision    recall  f1-score   support

          0       0.58      0.65      0.61       206
          1       0.58      0.51      0.54       198

avg / total       0.58      0.58      0.58       404

[[133  73]
 [ 97 101]]


In [30]:
print(confusion_matrix(y_test,predictions))

[[177  29]
 [ 15 183]]


In [62]:
from sklearn import metrics
print(metrics.accuracy_score(y_test, predictions))

0.579207920792


In [33]:
odd=1
for i in range(0,49):
    i=odd+i
    from sklearn.neighbors import KNeighborsClassifier
    knn = KNeighborsClassifier(n_neighbors=i,
                           p=2, metric='minkowski')
    knn.fit(X_train, y_train)
    predictions = knn.predict(X_test)
    from sklearn import metrics
    print(metrics.accuracy_score(y_test, predictions))

0.89603960396
0.878712871287
0.883663366337
0.883663366337
0.891089108911
0.863861386139
0.868811881188
0.834158415842
0.85396039604
0.841584158416
0.84900990099
0.829207920792
0.821782178218
0.819306930693
0.831683168317
0.804455445545
0.816831683168
0.799504950495
0.79702970297
0.774752475248
0.774752475248
0.752475247525
0.769801980198
0.764851485149
0.759900990099
0.730198019802
0.740099009901
0.710396039604
0.710396039604
0.69801980198
0.70297029703
0.695544554455
0.688118811881
0.663366336634
0.673267326733
0.665841584158
0.665841584158
0.665841584158
0.660891089109
0.648514851485
0.65099009901
0.64603960396
0.631188118812
0.64603960396
0.636138613861
0.638613861386
0.638613861386
0.626237623762
0.626237623762


In [57]:
import numpy as np
a=len(np.arange(1,100,2))
b=np.arange(1,100,2)
for i in range(1,a):
   # print(b[i])
    from sklearn.neighbors import KNeighborsClassifier
    knn = KNeighborsClassifier(n_neighbors=b[i],
                           p=2, metric='minkowski')
    knn.fit(X_train, y_train)
    predictions = knn.predict(X_test)
    from sklearn import metrics
    print(metrics.accuracy_score(y_test, predictions))

0.883663366337
0.891089108911
0.868811881188
0.85396039604
0.84900990099
0.821782178218
0.831683168317
0.816831683168
0.79702970297
0.774752475248
0.769801980198
0.759900990099
0.740099009901
0.710396039604
0.70297029703
0.688118811881
0.673267326733
0.665841584158
0.660891089109
0.65099009901
0.631188118812
0.636138613861
0.638613861386
0.626237623762
0.623762376238
0.613861386139
0.621287128713
0.611386138614
0.611386138614
0.611386138614
0.601485148515
0.601485148515
0.586633663366
0.591584158416
0.581683168317
0.584158415842
0.581683168317
0.586633663366
0.601485148515
0.591584158416
0.594059405941
0.596534653465
0.591584158416
0.579207920792
0.576732673267
0.579207920792
0.574257425743
0.584158415842
0.579207920792


In [51]:
a=len(np.arange(1,100,2))
print(a)

50


In [43]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

# KNN Regression


In [83]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as pt
import numpy as np
import pandas as pd
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
%matplotlib inline
df=pd.read_csv("C:\\Users\\29265\\Downloads\\data.csv")

In [88]:
y=df['duration_ms']
x=df.drop(['duration_ms','song_title','artist'],axis=1)

In [89]:
from sklearn.preprocessing import MinMaxScaler
pd.DataFrame(MinMaxScaler().fit_transform(x)).head()

0         1         2         3         4         5         6   \
0  0.000000  0.010248  0.824826  0.426363  0.022439  0.181818  0.153862   
1  0.000496  0.199998  0.720418  0.350081  0.006260  0.090909  0.124395   
2  0.000992  0.034570  0.830626  0.403987  0.000240  0.181818  0.147548   
3  0.001488  0.607034  0.431555  0.328723  0.522541  0.454545  0.077247   
4  0.001984  0.180902  0.645012  0.555533  0.524590  0.454545  0.442223   

         7    8         9         10    11        12   13  
0  0.741141  1.0  0.514441  0.596033  0.75  0.262432  1.0  
1  0.692162  1.0  0.071005  0.654474  0.75  0.577936  1.0  
2  0.791369  1.0  0.335351  0.158539  0.75  0.144379  1.0  
3  0.544709  1.0  0.003784  0.225162  0.75  0.203928  1.0  
4  0.654132  0.0  0.058393  0.735659  0.75  0.908065  1.0

In [91]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,
                                                    train_size=0.8,     random_state=42)

In [92]:
from sklearn.neighbors import KNeighborsRegressor
neigh = KNeighborsRegressor(n_neighbors=2)
neigh.fit(X_train, y_train) 
#KNeighborsRegressor(...)
 #print(neigh.predict([[1.5]]))
#predictions = knn.predict(X_test)
#from sklearn import metrics
#print(metrics.accuracy_score(y_test, predictions))

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=2, p=2,
          weights='uniform')

In [93]:
predictions = neigh.predict(X_test)
predictions


array([ 291220. ,  209113.5,  314328. ,  273734.5,  255646.5,  195554. ,
        210659. ,  226859. ,  247186.5,  229401. ,  208511. ,  186461. ,
        234007. ,  286866. ,  219680. ,  220367. ,  199796. ,  244726.5,
        208260. ,  191673.5,  226766.5,  249140. ,  196966. ,  228160. ,
        186116. ,  247889.5,  350481. ,  216770.5,  411162. ,  321766.5,
        224967. ,  208966.5,  256901. ,  182713.5,  231720. ,  244125.5,
        386529. ,  194431. ,  234007. ,  285463.5,  320413. ,  173458.5,
        294067. ,  179710. ,  202885.5,  332654.5,  321766.5,  342860. ,
        219808.5,  462380. ,  178769. ,  231387.5,  649783.5,  268959. ,
        292786.5,  212586.5,  237933.5,  207957. ,  239007. ,  201133.5,
        224533.5,  184887.5,  211928.5,  202197.5,  188173. ,  323715. ,
        350266.5,  224471. ,  181720. ,  198369.5,  244826.5,  242605.5,
        234647. ,  234647. ,  189602. ,  236074.5,  192562. ,  179813.5,
        266103.5,  392580. ,  218648. ,  182713.5, 

In [94]:
from sklearn import metrics
print(metrics.accuracy_score(y_test, predictions))

ValueError: Can't handle mix of multiclass and continuous

In [97]:
y_test-predictions

1555     50447.0
526     177793.5
393     -94574.0
1788   -128027.5
433     -10633.5
1159     19313.0
1090     97251.0
429      60968.0
1801    -22338.5
530     -88096.0
1208    -12658.0
1454     -3741.0
1910    -23007.0
1619    -96711.0
1022    -31867.0
678     114789.0
1477     89081.0
124     -18393.5
1900     -8407.0
462      15822.5
1858    -58286.5
1971    -46073.0
1001    -20377.0
1728      7693.0
1974     24951.0
1299    -46106.5
1593   -262776.0
1242     -1720.5
544    -163802.0
1558    -81673.5
          ...   
266     -17410.0
1261    -34593.0
1441   -276552.5
67      -24147.5
1848     11567.0
1814     76699.5
680      63044.0
485     128026.0
480      25536.0
1422    -15473.5
706       5210.0
548     193201.5
1423     50742.5
427      45246.5
1646    -43940.0
1488     62018.0
479     119497.0
450     182197.5
925       9182.0
617      14407.0
1542   -428050.5
1591    -80986.0
1671     89788.5
943     -64966.0
1355    -24603.5
1112    -12614.0
693     -49843.0
1493    -19244

In [95]:
metrics.mean_squared_error(y_test,predictions)

8612327531.8459167