In [1]:
import numpy as np
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
a=[[1,2,3],[1,1,1],[0,2,3]]
np.array(a)
np.zeros((5,5))
np.ones((5,4))
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [1]:
a=[[1,2,3],[1,1,1],[0,2,3]]
np.array(a)

NameError: name 'np' is not defined

In [15]:
np.random.rand(10)

array([0.40743311, 0.26008991, 0.56110418, 0.89709499, 0.21520917,
       0.50562565, 0.11071244, 0.01751814, 0.82051154, 0.30118553])

In [16]:
np.random.randn(10)

array([ 1.657569  ,  0.10868185, -1.04864591, -0.13992567, -1.90870166,
        1.00457245, -0.36508829, -1.05509483,  0.51157252,  1.22554337])

In [19]:
np.random.randint(10,100,10)

array([41, 75, 87, 91, 99, 72, 74, 57, 21, 15])

In [21]:
np.random.normal(10,3,2)

array([ 9.21866981,  6.926032  , 11.70640252, 16.74328401, 10.18008657])

In [42]:
a=[[1,2,3],[1,2,2]]
b=np.array(a)
b.sum()
b.max()
b.std()
b.mean()
b.shape


(2, 3)

In [41]:
a=[1,2,3,4]
b=np.array(a)
b.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [54]:
a=[1,2,3,4,5]
b=np.array(a)
b[0:3]=66
print (b)
d=b[0:3]
d[0]=99
d
b

[66 66 66  4  5]


array([99, 66, 66,  4,  5])

In [68]:
def f1():
    print('vikash')


In [69]:
f1()

TypeError: print() takes 0 positional arguments but 1 was given

In [78]:
def test1():
    print("this is test")

In [79]:
test1()

TypeError: print() takes 0 positional arguments but 1 was given