In [1]:
#campaign management
import pandas as pd
import numpy as np
test=pd.DataFrame(np.random.rand(20,3),columns=['sales','trans','profit'])


In [11]:
control=pd.DataFrame(np.random.rand(20,3),columns=['sales','trans','profit'])

In [13]:
a=[]
for i in test.columns:
    a.append(test[i].sum())

In [14]:
a

[11.206341457744246, 10.123921617030412, 11.292614975280818]

In [16]:
b=[]
for i in control.columns:
    b.append(control[i].sum())

In [17]:
a=np.array(a)
b=np.array(b)

In [18]:
lift=((a-b)/b)*100

In [19]:
lift

array([  4.42297504,  47.42964227,  15.02079459])

In [5]:
df

sales     trans    profit
0   0.898011  0.561994  0.969126
1   0.132329  0.097755  0.001973
2   0.376606  0.871199  0.106806
3   0.359509  0.414028  0.230107
4   0.690986  0.447426  0.966672
5   0.196136  0.709405  0.279154
6   0.723218  0.639741  0.616703
7   0.059421  0.559728  0.973608
8   0.048965  0.933978  0.484052
9   0.864654  0.169139  0.366789
10  0.735380  0.288980  0.362700
11  0.142817  0.741897  0.643726
12  0.328034  0.214859  0.989908
13  0.820394  0.252316  0.873443
14  0.120600  0.959010  0.180403
15  0.662292  0.224285  0.406819
16  0.266874  0.257983  0.038942
17  0.618734  0.228054  0.448024
18  0.844071  0.508115  0.470501
19  0.727575  0.116496  0.880869

In [6]:
import numpy as np
a=np.random.rand(20,3)

In [7]:
a.shape

(20, 3)

In [4]:
#agglomaerative cluster
df3=pd.read_excel("C:\\Users\\29265\\Desktop\\data.xlsx",sheetname='Sheet7')
df3
#df3["is_duplicate"]= df3.duplicated()
 
#df3.describe

'''
for i in range(0,len((df3['is_duplicate']))):
    if df3['is_duplicate'][i]=='True':
        df3.iloc[]
    print (i)
'''
    
    


"\nfor i in range(0,len((df3['is_duplicate']))):\n    if df3['is_duplicate'][i]=='True':\n        df3.iloc[]\n    print (i)\n"

In [22]:
import pandas as pd
df3=pd.read_excel("C:\\Users\\29265\\Desktop\\data.xlsx",sheetname='Sheet7')
df3
a=df3[df3.duplicated(keep=False)]
a

str  sales  units  txns
0  str1     34      1  2348
1  str1     34      1  2348
5  str6     40      1  2000
6  str1     34      1  2348
7  str6     40      1  2000

In [47]:
def FindDuplicateRow(df):
    a=df3[df3.duplicated(keep=False)]
    a

In [36]:
len(list(p.columns))

5

In [16]:
import scipy.cluster.hierarchy as sch
import matplotlib.pyplot as plt
dendrogram = sch.dendrogram(sch.linkage(df3, method = 'single'))
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Sales')
plt.show()

ValueError: could not convert string to float: 'str6'

In [11]:
a=['a','b','z']
b=['a','d','c','f','b']
for i in range(0,len(a)):
    for j in range(0,len(b)):
        if a[i]==b[j]:
            break
            #print('match')
            #print(a[i])
        else:
            print(a[i])

b
b
b
b
z
z
z
z
z


In [46]:
#return all dublicates value in table uniquly
b
z=b.drop_duplicates()
z

str sales units  txns
0  str1    34     1  2348
5  str6    40     1  2000

In [24]:
list(set(lst1)-set(lst2))

[1]

In [27]:
f=open('C:\\Users\\29265\\Desktop\\abc1.txt')
f.seek(0)
a=f.readlines()
a


['ConfigFileInfo:=Author:=Mriganka\n',
 'ConfigFileInfo:=CreatedDate:=2018-03-28\n',
 'ConfigFileInfo:=Version:=1.0\n',
 'ConfigFileInfo:=ModifiedDate:=2018-05-14\n',
 'ConfigFileInfo:=ModifiedBy:=Mriganka\n',
 "ConfigFileInfo:=ChangesHistory:=Changed CommercialName,OwnershipType,Status,District,Country,OutletType,RecordTypeName to Nullable fields defaulted with 'N/A'\n",
 '\n',
 '\n',
 'MetaData:=CustId:=StringType(18):=NonNullable\n',
 'MetaData:=CommercialName:=StringType(255):=Nullable\n',
 'MetaData:=CustomerCode:=StringType(18):=Nullable\n',
 'MetaData:=LegalName:=StringType(255):=Nullable\n',
 'MetaData:=OriginalPetraCustomer:=StringType(255):=Nullable\n',
 'MetaData:=OwningCustomer:=StringType(18):=Nullable\n',
 'MetaData:=IsVendor:=IntegerType:=Nullable\n',
 'MetaData:=KeyAccountType:=StringType(80):=Nullable\n',
 'MetaData:=Banner:=StringType(30):=Nullable\n',
 'MetaData:=OwnershipType:=StringType(30):=Nullable\n',
 'MetaData:=Status:=StringType(80):=Nullable\n',
 'MetaData:=

In [29]:
d={}
d['a']=1
d['b']=2
print(d)
len(d)

{'a': 1, 'b': 2}


2

In [65]:
import pandas as pd
a={'null value':['a','c','l']}
df1=pd.DataFrame(a)
df1

null value
0          a
1          c
2          l

In [14]:

def getFileName(path):
    
    b=a.split('\\')
    d=len(b)-1
    f=b[d]
    b=f.split('.')
    return b[0]

In [15]:
a='C:\\Users\\29265\\Desktop\\data.xlsx'
val=getFileName(a)
val

'data'

In [34]:
import xlsxwriter

# Create a new workbook and add a worksheet
workbook = xlsxwriter.Workbook('hyperlink.xlsx')
worksheet = workbook.add_worksheet('Hyperlinks')

# Format the first column
worksheet.set_column('A:A', 30)

# Add a sample alternative link format.
red_format = workbook.add_format({
    'font_color': 'red',
    'bold':       1,
    'underline':  1,
    'font_size':  12,
})

# Write some hyperlinks
worksheet.write_string('A1', 'ConfigFileName')  # Implicit format.
worksheet.write_url('A2', '#Hyperlinks!A1', string='config')
#worksheet.write_url('A3', 'http://www.python.org/', tip='Click here')
#worksheet.write_url('A4', 'http://www.python.org/', red_format)
#worksheet.write_url('A5', 'mailto:jmcnamara@cpan.org', string='Mail me')

# Write a URL that isn't a hyperlink
#worksheet.write_string('A11', 'http://www.python.org/')

workbook.close()

'''
import pandas as pd
df3=pd.read_excel("C:\\Users\\29265\\hyperlink.xlsx",sheetname='Hyperlinks')
df3
bb={'null':[23]}
df4=pd.DataFrame(bb)
df4
#writer = pd.ExcelWriter('Petra_Report.xlsx', engine='xlsxwriter')
df4.to_excel('C:\\Users\\29265\\hyperlink.xlsx', sheet_name='Hyperlinks',startcol=2,startrow=1)
#df4.to_excel(writer, sheet_name='Sheet2',startrow=2)
'''

'\nimport pandas as pd\ndf3=pd.read_excel("C:\\Users\\29265\\hyperlink.xlsx",sheetname=\'Hyperlinks\')\ndf3\nbb={\'null\':[23]}\ndf4=pd.DataFrame(bb)\ndf4\n#writer = pd.ExcelWriter(\'Petra_Report.xlsx\', engine=\'xlsxwriter\')\ndf4.to_excel(\'C:\\Users\\29265\\hyperlink.xlsx\', sheet_name=\'Hyperlinks\',startcol=2,startrow=1)\n#df4.to_excel(writer, sheet_name=\'Sheet2\',startrow=2)\n'

In [30]:
import pandas as pd
df = pd.DataFrame({'link':['=HYPERLINK("Petra_Report.xlsx#sheet2!E5", "some website")']})
df.to_excel('test.xlsx')

In [33]:
writer = pd.ExcelWriter('Petra_Report_link.xlsx', engine='xlsxwriter')
#dfblank
dfblank = pd.DataFrame({'link':['=HYPERLINK("Petra_Report_link.xlsx#sheet2!E5", "Config")'],'null':34})
dfblank.to_excel(writer, sheet_name='Summary_Report',startrow=2)
df4.to_excel(writer, sheet_name='Sheet2',startrow=2)

In [35]:
import pandas as pd
df_data=pd.read_csv("C:\\Users\\29265\\Desktop\\Data_Dimension_Cust.csv")
df_count_val=df_data.CustId.value_counts()
df_count_val=pd.DataFrame(df_count_val)#columns=['value','count']
#df_count_val
df_count_val_T=df_count_val.T

In [49]:
a=list(df_count_val_T['0016E00000ZXdVfQA3'])

In [51]:
a

[2]

In [52]:
pd.test()

running: pytest --skip-slow --skip-network C:\Users\29265\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas
============================= test session starts =============================
platform win32 -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: C:\Users\29265, inifile:
collected 10236 items / 2 skipped

AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\test_algos.py ........................................................................................
AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\test_base.py .........................
AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\test_categorical.py ...................................................................................FFFFFF..FFFFFF................................................
AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\test_common.py ..............
AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\t

AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\io\test_packers.py .....................................s.s.ss.s..........
AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\io\test_pickle.py ..........................................
AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\io\test_pytables.py ....................s.................................................................................x.......s....s........................................s..
AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\io\test_s3.py .
AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\io\test_sql.py .................................................................................................s....ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss................s....................................s................s.......

        idx = pd.period_range('2011-01-01 09:00', freq='H', periods=5)
        c = pd.Categorical(idx)
        exp = """[2011-01-01 09:00, 2011-01-01 10:00, 2011-01-01 11:00, 2011-01-01 12:00, 2011-01-01 13:00]
    Categories (5, period[H]): [2011-01-01 09:00, 2011-01-01 10:00, 2011-01-01 11:00, 2011-01-01 12:00,
                                2011-01-01 13:00]"""  # noqa
    
>       assert repr(c) == exp
E       AssertionError: assert '[2011-01-01 ...-01-01 13:00]' == '[2011-01-01 0...-01-01 13:00]'
E         Skipping 180 identical leading characters in diff, use -v to show
E         - -01 12:00, 2011-01-01 13:00]
E         + -01 12:00,
E         +                             2011-01-01 13:00]

AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tests\test_categorical.py:2255: AssertionError
_________ TestCategoricalAsBlock.test_categorical_repr_period_ordered _________

self = <pandas.tests.test_categorical.TestCategoricalAsBlock object at 0x000001991F6651D0>

    def test_c

    
        try:
            try:
                h.request(req.get_method(), req.selector, req.data, headers,
>                         encode_chunked=req.has_header('Transfer-encoding'))

AppData\Local\Continuum\Anaconda3\lib\urllib\request.py:1318: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <http.client.HTTPSConnection object at 0x000001991FE935C0>
method = 'GET'
url = '/vincentarelbundock/Rdatasets/master/csv/HistData/Guerry.csv'
body = None
headers = {'Connection': 'close', 'Host': 'raw.github.com', 'User-Agent': 'Python-urllib/3.6'}

    def request(self, method, url, body=None, headers={}, *,
                encode_chunked=False):
        """Send a complete request to the server."""
>       self._send_request(method, url, body, headers, encode_chunked)

AppData\Local\Continuum\Anaconda3\lib\http\client.py:1239: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <http.client.HTTPSConnection objec

SystemExit: 1

C:\Users\29265\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [47]:
df_count_val_T
df_count_val_T.loc[0:1,'0016E00000ZXdVfQA3']

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'int'>

In [44]:
df_count_val_T.iloc[0:1,['0016E00000ZXdVfQA3']]

TypeError: cannot perform reduce with flexible type

In [3]:
len(b)

5

In [4]:
b[4]

'data.xlsx'

In [3]:
#ROC curve 
import numpy as np
from sklearn import metrics
y = np.array([1, 1, 2, 2])
scores = np.array([0.1, 0.4, 0.35, 0.8])
fpr, tpr, thresholds = metrics.roc_curve(y, scores, pos_label=2)
print(fpr)
#array([ 0. ,  0.5,  0.5,  1. ])
print(tpr)
#array([ 0.5,  0.5,  1. ,  1. ])
print(thresholds)
#array([ 0.8 ,  0.4 ,  0.35,  0.1 ])

[ 0.   0.5  0.5  1. ]
[ 0.5  0.5  1.   1. ]
[ 0.8   0.4   0.35  0.1 ]


In [44]:
p=[]
z={'cust':1,'b':3}
p.append(z)
df2=pd.DataFrame(p)


In [48]:
writer = pd.ExcelWriter('pandas_simple.xlsx', engine='xlsxwriter')
df1.to_excel(writer, sheet_name='Sheet1')  # Default position, cell A1.
df2.to_excel(writer, sheet_name='Sheet1', startcol=3)
writer.save() 

In [47]:
pwd


'C:\\Users\\29265'

In [67]:
from openpyxl import load_workbook

wb = load_workbook('C:\\Users\\29265\\pandas_simple.xlsx') 
ws = wb.get_sheet_by_name("Sheet1")

link = "pandas_simple.xlsx#sheet2!E5"

ws.cell(row=1, column=1).hyperlink = (link)

wb.save('C:\\Users\\29265\\pandas_simple.xlsx')

In [32]:
for i in d:
    if d[i]==3:
        print(d[i])

In [34]:
x=['a','b','c']
y=['x','z','l','a','c']
for i in range(0,len(x)):
    for j in range(0,len(y)):
        if x[i]==y[j]:
            print(x[i])

a
c


In [7]:
lst1=[1,2,3]
lst2=[1,2,4]
final=list(set(lst1) & set(lst2))
final

[1, 2]

In [ ]:
for i in len(lst1):
    for j in len(final):
        if lst1[i]==final[j]:
            
    

In [13]:
A=['a','b']
B=['b']
def a(x,y):
    return list(set(x)-set(y))


In [14]:
b=a(A,B)
b

['a']

In [17]:
insection

[9, 4, 1]

In [18]:
list(set(lst1) & set(insection))

[9, 4, 1]

In [19]:
set(lst1) == set(insection)

True

In [ ]:
list(set(lst1) & set(lst2))

In [29]:
#agglomaerative cluster
import pandas as pd
df3=pd.read_excel("C:\\Users\\29265\\Desktop\\data.xlsx",sheetname='Sheet6')
df3


sales   units  trans
0      2     NaN      6
1      1     NaN      6
2      4     NaN      7
3      7     NaN      4
4      6     NaN      5
5     23     NaN     23
6     89    90.0     56
7   2000  2100.0   1000

In [30]:
def countNullValue_RemoveColHAve30Percent(df):
    total = df.isnull().sum().sort_values(ascending = False)
    percent = (df.isnull().sum()/df.isnull().count()*100).sort_values(ascending = False)
  
    missing_application_train_data=pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
 
    missing_application_train_data=missing_application_train_data.T
    for i in missing_application_train_data.columns:
        a=missing_application_train_data[i]
        if a[1]>30:
            df.drop(i,axis=1,inplace=True)
    return df

In [31]:
dfnew=countNullValue(df3)
dfnew

sales  trans
0      2      6
1      1      6
2      4      7
3      7      4
4      6      5
5     23     23
6     89     56
7   2000   1000

In [6]:
a='abcv'
#a[1:2]='s'
id(a[2])

1548828918648

In [1]:
a=()
a

()

In [5]:
#list set,dictionary  is mutual but string ,number,tuple are immutable
a=(1,2,'3')
a[0]='2'

TypeError: 'tuple' object does not support item assignment

In [6]:
a={'a':1,'b':2}
a

{'a': 1, 'b': 2}

In [7]:
a['a']=2
a

{'a': 2, 'b': 2}

In [22]:
class Demo:
    a='vikash'
    def __init__(self,name):
        self.name=name
    def name1(self):
        print(self.name)
ob=Demo('kumar')
ob.a
ob.name
ob.name1()

kumar


In [23]:
Demo.a

'vikash'

In [24]:
sum(x*x for x in range(1,10))


285

In [26]:
sum(x*x for x in range(1,10))

285

In [28]:
class poly:
    def sound(self):
        print('dog')
class more:
    def sound(self):
        print('cow')
ob1=poly()
ob1.sound()

dog


In [29]:
ob2=more()
ob2.sound()

cow


In [30]:
lambda x:x+1

<function __main__.<lambda>>

In [37]:
def ab(x):
    return x+1
map(ab,[4,5])


In [38]:
list_a = [1, 2, 3]
list_b = [10, 20, 30]
  
map(lambda x, y: x + y, list_a, list_b) # Output: [11, 22, 33]

In [41]:
a='vikash'
print(id(a))

2058914333392


In [43]:
a='kumar'
a[0]='g'
print(id(a))

TypeError: 'str' object does not support item assignment

In [47]:
a=[2,3,4]
b=[2,3,6]
a.append(b)
print(a)

[2, 3, 4, [2, 3, 6]]


In [48]:
a=[2,3,4]
b=[2,3,6]
a.extend(b)
print(a)

[2, 3, 4, 2, 3, 6]


In [51]:
a=[2,3,43]
b=2
a.append(b)
a

[2, 3, 43, 2]

In [58]:
x=[2,3]
y=9
try:
    x.extend(y)
    x
except:
    print("error")

error


In [60]:
sum=lambda x:x*x
sum(2)

4

In [64]:
a=[2,3,4]
x=map(lambda x:x+2,a)
list(x)

[4, 5, 6]

In [68]:
# filter
a=[1,2,3,4]
p=filter(lambda x: x%2==0,a)
list(p)

[2, 4]

In [73]:
a='vikash'
sum=''
for i in a:
    sum=i+sum
print(sum)

hsakiv


In [74]:
a[::-1]

'hsakiv'

In [77]:
def NameSum(*args):#*args will give list of value with non keyword
    nameadd=''
    for i in args:
        nameadd=nameadd+i
    print(nameadd)
NameSum('vikash','kumar','ravi')

vikashkumarravi


In [89]:
#**kargs#variable-length argument dictionary to a function.

def getCid(**kargs):
    for key,val in kargs.items():
        print(str(key)+": "+val)
        print('my key for {} is {} '.format(key,val))
getCid(k='vikash',v='kumar')

k: vikash
my key for k is vikash 
v: kumar
my key for v is kumar 


In [83]:
def print_values(**kwargs):
    for key, value in kwargs.items():
        print("The value of {} is {}".format(key, value))

print_values(
            name_1="Alex",
            name_2="Gray",
            name_3="Harper",
            name_4="Phoenix",
            name_5="Remy",
            name_6="Val"
        )

The value of name_1 is Alex
The value of name_2 is Gray
The value of name_3 is Harper
The value of name_4 is Phoenix
The value of name_5 is Remy
The value of name_6 is Val


In [91]:
#to=Email[0].replace('TO:\xa0','')
a='vikash@'
print(id(a))
a=a.replace('@','')
print(id(a))

2058914417496
2058914467488


In [94]:
for i in range(0,4):
    print(i)

0
1
2
3


In [95]:
for i in xrange(0,4):
    print(i)

NameError: name 'xrange' is not defined

In [ ]:
#decorator #generator


In [61]:
#CODE
#input='abcacd'
def getkey(input):
    key=[]
    for i in input:
        #print(i)
        if i not in key:
            key.append(i)
    return key


In [62]:
def getOccurencerr(input,key):
    result=[]
    for i in key:#['a', 'b', 'c', 'd']
        count=0
        for j in input:#abcacd
            if i==j:
                count=count+1
        dict={i:count}
        result.append(dict)
    return result


In [63]:
key=getkey('abcacd')
#res=getOccurencerr('abcacd',key)
#res

In [65]:
#key value camparison then pick
xx='abcacd'
xx=list(xx)
for i in range(0,len(xx)):
    x=xx[i]
    res=getOccurencerr(xx,key)
    for i in range(0,len(res)):
        #need to check the key value with character
        try:
            if(res[i][x])>1:
                print("for key: "+x+"occurence is :"+res[i][x])
        except:
           # print("ex")
            continue
            

In [58]:
p=[{'a': 2}, {'b': 1}, {'c': 2}, {'d': 1}]

In [53]:
p[1]['b']

1

In [90]:
a=[1,2,6]
a[::1]

[1, 2, 6]

In [22]:
key

['a', 'b', 'c', 'd']

In [31]:
key=getkey('zbzcacd')

res=[]
for i in key:#['a', 'b', 'c', 'd']
    count=0
    for j in input:#abcacd
        if i==j:
            count=count+1
    dict={i:count}
    res.append(dict)
            

In [32]:
key

['z', 'b', 'c', 'a', 'd']

In [33]:
felement=key[0]
felement


'z'

In [29]:
res

[{'a': 2}, {'b': 1}, {'c': 2}, {'d': 1}]

In [67]:
def abc():
    return a

In [68]:
abc()

[{'b': 1}]

In [85]:
from collections import Counter
a=[1,2,2,2,'h']
b=Counter(a)
b['h']

1

In [118]:
a='aabcd'
b='abef'
x=[]
y=[]
for i in a:
    x.append(i)
for i in b:
    y.append(i)

In [119]:
x=set(x)
y=set(y)

In [120]:
p=x-y
p
temp=''
for i in p:
    temp=temp+i
temp

'dc'

In [121]:
q=y-x
for i in q:
    temp=temp+i
temp

'dcef'

In [111]:
p.append(q)
p

AttributeError: 'set' object has no attribute 'append'

In [6]:
input=[2342,1234,2345,7689]
#find the odd one
#1st sort order in each entry
#then use loop to check for all the input
#a=2343
for k in input:
    a=str(k)
    temp=[]
    for i in a:
        temp.append(i)
    temp
    for i in temp:
        for j in temp:
            if i>j:  
                print(a)
                break

2342
2342
1234
1234
1234
2345
2345
2345
7689
7689
7689
